DROP TABLE user_info;;/*SkipError*/
DROP TABLE role;;/*SkipError*/
DROP TABLE user_role;;/*SkipError*/
DROP TABLE user_group;;/*SkipError*/
DROP TABLE user_group_user_info;;/*SkipError*/
DROP TABLE user_group_role;;/*SkipError*/
DROP TABLE menu;;/*SkipError*/
DROP TABLE page_element;;/*SkipError*/
DROP TABLE power;;/*SkipError*/
DROP TABLE power_menu;;/*SkipError*/
DROP TABLE power_page_element;;/*SkipError*/
DROP TABLE opetation;;/*SkipError*/
DROP TABLE power_opt;;/*SkipError*/
DROP TABLE role_power;;/*SkipError*/
