CREATE TABLE zly_file(
    CREATED_TIME TIMESTAMP NOT NULL,
    USER_ID VARCHAR(32) NOT NULL,
    FILE_ID VARCHAR(32) NOT NULL,
    FILE_HASH VARCHAR(1024) NOT NULL,
    FILE_NAME VARCHAR(128) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    PRIMARY KEY (FILE_ID)
);;

COMMENT ON COLUMN zly_file.CREATED_TIME IS '上传时间';;
COMMENT ON COLUMN zly_file.USER_ID IS '上传用户ID';;
COMMENT ON COLUMN zly_file.FILE_ID IS '文件ID';;
COMMENT ON COLUMN zly_file.FILE_HASH IS '文件hash';;
COMMENT ON COLUMN zly_file.FILE_NAME IS '文件名称';;
COMMENT ON COLUMN zly_file.FILE_SIZE IS '文件大小';;


CREATE TABLE file_storage(
    STORAGE_ID VARCHAR(32) NOT NULL,
    FILE_ID VARCHAR(32) NOT NULL,
    PRIMARY KEY (STORAGE_ID,FILE_ID)
);;

COMMENT ON COLUMN file_storage.STORAGE_ID IS '空间ID';;
COMMENT ON COLUMN file_storage.FILE_ID IS '文件ID';;